-- MySQL Script generated by MySQL Workbench
-- Tue Jun 13 18:23:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema instituto2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `instituto2` ;

-- -----------------------------------------------------
-- Schema instituto2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `instituto2` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `instituto2` ;

-- -----------------------------------------------------
-- Table `Alumno_Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alumno_Curso` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Alumno_Curso` (
  `idAlumno_Curso` INT NOT NULL AUTO_INCREMENT,
  `idAlumno` INT NOT NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`idAlumno_Curso`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alumnos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Alumnos` (
  `idAlumno` INT NOT NULL AUTO_INCREMENT,
  `alumnoNombre` VARCHAR(45) NULL,
  `alumnoApellido` VARCHAR(45) NULL,
  `alumnoFechaDeIngreso` DATE NULL,
  `alumnoDNI` VARCHAR(10) NULL,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cursos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cursos` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `cursoNombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Docente_Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Docente_Curso` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Docente_Curso` (
  `idDocente_Curso` INT NOT NULL AUTO_INCREMENT,
  `idDocente` INT NOT NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`idDocente_Curso`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Docentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Docentes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Docentes` (
  `idDocente` INT NOT NULL AUTO_INCREMENT,
  `docenteNombre` VARCHAR(45) NULL,
  `docenteApellido` VARCHAR(45) NULL,
  `docenteFechaDeRegistro` DATE NULL,
  `docenteDNI` VARCHAR(10) NULL,
  PRIMARY KEY (`idDocente`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
